
trigger:
- master
pr:
  branches:
    include:
    - master

pool: 'Default'

steps:

    - task: Maven@2

      inputs:

        mavenPomFile: 'DeepSpace/pom.xml'

        jdkVersionOption: 1.8

        jdkArchitectureOption: x64

        checkStyleRunAnalysis: true

        pmdRunAnalysis: true

        findBugsRunAnalysis: true
